config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  root to: 'pages#index'

  post "/" => 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  validates :ticker, presence: true
  validate :valid_ticker?

  def valid_ticker?
    StockQuote::Stock.new(api_key: "pk_03f609bd3ac74f70b35c77418535c946")
    if ticker
      begin
        @ticker = StockQuote::Stock.quote(ticker)
      rescue => e
        errors.add(:ticker, "can't be invalid. Insert a valid symbol")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :index ]

  def home
  end

  def index
    @api = StockQuote::Stock.new(api_key: "pk_03f609bd3ac74f70b35c77418535c946")
    if params[:ticker] == ""
      @nothing = "You forgot to enter a Symbol"
    elsif params[:ticker]
      begin
        @stock = StockQuote::Stock.quote(params[:ticker])
      rescue => e
        @error = "Sorry, maybe you should try again, the symbol you wrote doesn't exist"
      end
   end
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all.where(user_id: current_user)
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @user = current_user
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create

    @stock = Stock.new(stock_params)
    @user = current_user
    @stock.user = @user
    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockapi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <br/><br/>
    <div class="container">
    <%= render 'shared/flashes' %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Stocking App</h1>

<% @api %>
<%= form_tag root_path, :method => 'POST' do %>
  <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
  <%= submit_tag "Search" %>
<% end %>

<% if @stock %>
  <%= @stock.company_name %>
  <%= @stock.latest_price %>
<% elsif @nothing %>
  <%= @nothing %>
<% end %>
<% if @error %>
  <%= @error %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-stockapi">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://socialimpact.com/wp-content/uploads/2021/03/logo-placeholder.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add stock", new_stock_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Show stocks", stocks_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stocks/_form.html.erb
<%= simple_form_for(@stock) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :ticker %>

  </div>

  <div class="form-actions">

    <%= f.button :submit %>
  </div>

<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
 <div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Stocks</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Company</th>
        <th>Ticker</th>
        <th>Current Price</th>
        <th>Market Cap</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @stocks.each do |stock| %>
        <%  StockQuote::Stock.new(api_key: "pk_03f609bd3ac74f70b35c77418535c946") %>
        <% if stock.ticker == "" %>
          <% @nothing = "You forgot to enter a Symbol" %>
        <% elsif stock.ticker %>
          <% begin %>
          <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
          <% rescue => e %>
          <% @error = "Sorry, maybe you should try again, the symbol you wrote doesn't exist" %>
          <% end %>
        <% end %>
        <tr>
          <td><%= @ticker.company_name %></td>
          <td><%= @ticker.symbol %></td>
          <td>USD <%= number_with_precision(@ticker.iex_realtime_price, :precision => 2, :delimiter => ",") %></td>
          <td>USD <%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ",") %></td>
          <td><center><%= link_to 'Show', stock %></center></td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Stock', new_stock_path %>
</div>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% if @stock.user == current_user %>
<%  StockQuote::Stock.new(api_key: "pk_03f609bd3ac74f70b35c77418535c946") %>
<% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Ticker:</strong>
    <%= @stock.ticker %>
  </p>
  <strong>Company Name:</strong><%= @ticker.company_name %><br/>
  <strong>Current Ask:</strong><%= @ticker.iex_ask_price %><br/>
  <strong>Change Percent:</strong><%= @ticker.change_percent %><br/>
  <strong>Price/Earning Ratio:</strong><%= @ticker.pe_ratio %><br/>
  <strong>Market Cap:</strong><%= @ticker.market_cap %><br/>
  <strong>Stock Open:</strong><%= @ticker.open %><br/>
  <strong>Days's Range:</strong><%= @ticker.low %> - <%= @ticker.high %><br/>
  <strong>Year High:</strong><%= @ticker.week52_high %><br/>
  <strong>Year Low:</strong><%= @ticker.week52_low %><br/>
  <% @chart = StockQuote::Stock.batch("chart", @ticker.symbol,'6m') %>
  <strong>Chart:</strong><%= @chart %><br/>
  <%= link_to 'Edit', edit_stock_path(@stock) %> |
  <%= link_to 'Back', stocks_path %>
<% end %>